version: "3"

services:
  bankGo:
    image: postgres:alpine
    container_name: bankGo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    networks:
      - postgres-network

networks:
  postgres-network:
